# Generated by Django 5.1.1 on 2024-09-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_merge_20240925_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_images/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='exam_thumbnails/'),
        ),
    ]
