# Generated by Django 5.1.1 on 2024-11-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_create_superuser'),
        ('exam', 'add_AI'),
        ('exam', 'add_ai_specialist'),
        ('exam', 'add_crt1'),
        ('exam', 'add_crt2'),
        ('exam', 'add_crt3'),
        ('exam', 'add_crt4'),
        ('exam', 'add_crt5'),
        ('exam', 'add_set1'),
        ('exam', 'add_set2'),
        ('exam', 'add_set3'),
        ('exam', 'add_set4'),
        ('exam', 'add_set5'),
        ('exam', 'add_set6'),
    ]

    operations = [
    ]
