from django.db import migrations, transaction

def add_ai_specialist(apps, schema_editor):
    Exam = apps.get_model('exam', 'Exam')
    Question = apps.get_model('exam', 'Question')
    Answer = apps.get_model('exam', 'Answer')
    Group = apps.get_model('exam', 'Group')


    with transaction.atomic():
        group, created = Group.objects.get_or_create(
            name='AI Specialist-Exams',
            defaults={'description': 'Group for AI related exams'}
        )
        # Create an exam instance and associate it with the group
        exam = Exam.objects.create(title='#AI Specialist-Exams')

        # If you want to add the exam to the group (assuming a many-to-many relation):
        group.exams.add(exam)

        # Define questions and answers
        questions_data = [
            {
                'text': 'An AI Specialist needs to create a Sales Email with a custom prompt template. They need to ground on the following data: Opportunity Products, Events near the customer, Tone and voice examples. How should the AI Specialist obtain related items?',
                'answers': [
                    ('Call prompt-initiated flow to fetch and ground the required data.', True),
                    ('Create a flex template that takes the records in question as inputs.', False),
                    ('Utilize a standard email template and manually insert the required data fields.', False),
                ],
            },
            {
                'text': 'Universal Containers wants to be able to detect with a high level confidence if content generated by a large language model (LLM) contains toxic language. Which action should an AI Specialist take in the Trust Layer to confirm toxicity is being appropriately managed?',
                'answers': [
                    ('Access the Toxicity Detection log in Setup and export all entries where is Toxicity Detected is true.', False),
                    ('Create a flow that sends an email to a specified address each time the toxicity score from the response exceeds a predefined threshold.', False),
                    ('Create a Trust Layer audit report within Data Cloud that uses a toxicity detector type filter to display toxic responses and their respective scores.', True),
                ],
            },
            {
                'text': 'Amid their busy schedules, sales reps at Universal Containers dedicate time to follow up with prospects and existing clients via email regarding renewals or new deals. They spend many hours throughout the week reviewing past communications and details about their customers before performing their outreach. Which standard Copilot action helps sales reps draft personalized emails to prospects by generating text based on previous successful communications?',
                'answers': [
                    ('Einstein Copilot Action: Find Similar Opportunities', False),
                    ('Einstein Copilot Action: Draft or Revise Sales Email', True),
                    ('Einstein Copilot Action: Summarize Record', False),
                ],
            },
            {
                'text': 'Based on the user utterance, "Show me all the customers in New York", which standard Einstein Copilot action will the planner service use?',
                'answers': [
                    ('Query Records', False),
                    ('Select Records', True),
                    ('Fetch Records', False),
                ],
            },
            {
                'text': 'The sales team at a hotel resort would like to generate a guest summary about the guests\' interests and provide recommendations based on their activity preferences captured in each guest profile. They want the summary to be available only on the contact record page. Which AI capability should the team use?',
                'answers': [
                    ('Einstein Copilot', False),
                    ('Prompt Builder', True),
                    ('Model Builder', False),
                ],
            },
            {
                'text': 'What should an AI Specialist consider when using related list merge fields in a prompt template associated with an Account object in Prompt Builder?',
                'answers': [
                    ('The Activities related list on the Account object is not supported because it is a polymorphic field.', True),
                    ('If person accounts have been enabled, merge fields will not be available for the Account object.', False),
                    ('Prompt generation will yield no response when there is no related list associated with an Account in runtime.', False),
                ],
            },
            {
                'text': 'An AI Specialist wants to use the related lists from an account in a custom prompt template. What should the AI Specialist consider when configuring the prompt template?',
                'answers': [
                    ('The text encoding (for example, UTF-8, ASCII) option', False),
                    ('The maximum number of related list merge fields', True),
                    ('The choice between XML and JSON rendering formats for the list', False),
                ],
            },
            {
                'text': 'Universal Containers’ data science team is hosting a generative large language model (LLM) on Amazon Web Services (AWS). What should the team use to access externally-hosted models in the Salesforce Platform?',
                'answers': [
                    ('Model Builder', True),
                    ('App Builder', False),
                    ('Copilot Builder', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) wants to enable its sales reps to explore opportunities that are similar to previously won opportunities by entering the utterance, "Show me other opportunities like this one." How should UC achieve this in Einstein Copilot?',
                'answers': [
                    ('Use the standard Copilot action.', True),
                    ('Create a custom Copilot action calling a flow.', False),
                    ('Create a custom Copilot action calling an Apex class.', False),
                ],
            },
            {
                'text': 'An AI Specialist wants to ground a new prompt template with the User related list. What should the AI Specialist consider?',
                'answers': [
                    ('The User related list should have View All access.', False),
                    ('The User related list needs to be included on the record page.', False),
                    ('The User related list is not supported in prompt templates.', True),
                ],
            },
            {
                'text': 'Universal Containers wants to reduce overall agent handling time by minimizing the time spent typing routine answers for common questions in-chat, and reducing the post-chat analysis by suggesting values for case fields. Which combination of Einstein for Service features enables this effort?',
                'answers': [
                    ('Einstein Service Replies and Work Summaries', False),
                    ('Einstein Reply Recommendations and Case Summaries', False),
                    ('Einstein Reply Recommendations and Case Classification', True),
                ],
            },
            {
                'text': 'Universal Containers is very concerned about security compliance and wants to understand: Which prompt text is sent to the large language model (LLM), how it is masked, and the masked response. What should the AI Specialist recommend?',
                'answers': [
                    ('Ingest the Einstein Shield Event logs into CRM Analytics.', False),
                    ('Review the debug logs of the running user.', False),
                    ('Enable audit trail in the Einstein Trust Layer.', True),
                ],
            },
            {
                'text': 'Universal Containers (UC) is looking to enhance its operational efficiency. UC has recently adopted Salesforce and is considering implementing Einstein Copilot to improve its processes. What is a key reason for implementing Einstein Copilot?',
                'answers': [
                    ('Improving data entry and data cleansing', False),
                    ('Allowing AI to perform tasks without user interaction', False),
                    ('Streamlining workflows and automating repetitive tasks', True),
                ],
            },
            {
                'text': 'Universal Containers (UC) wants to improve the efficiency of addressing customer questions and reduce agent handling time with AI-generated responses. The agents should be able to leverage their existing knowledge base and identify whether the responses are coming from the large language model (LLM) or from Salesforce Knowledge. Which step should UC take to meet this requirement?',
                'answers': [
                    ('Turn on Service AI Grounding, Grounding with Case, and Service Replies.', False),
                    ('Turn on Service Replies, Service AI Grounding, and Grounding with Knowledge.', True),
                    ('Turn on Service AI Grounding and Grounding with Knowledge.', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) noticed an increase in customer contract cancellations in the last few months. UC is seeking ways to address this issue by implementing a proactive outreach program to customers before they cancel their contracts and is asking the Salesforce team to provide suggestions. Which use case functionality of Model Builder aligns with UC\'s request?',
                'answers': [
                    ('Product recommendation prediction', False),
                    ('Customer churn prediction', True),
                    ('Contract Renewal Date prediction', False),
                ],
            },
            {
                'text': 'Universal Containers wants to make a sales proposal and directly use data from multiple unrelated objects (standard and custom) in a prompt template. What should the AI Specialist recommend?',
                'answers': [
                    ('Create a Flex template to add resources with standard and custom objects as inputs.', True),
                    ('Create a prompt template passing in a special custom object that connects the records temporarily.', False),
                    ('Create a prompt template-triggered flow to access the data from standard and custom objects.', False),
                ],
            },
            {
                'text': 'What is an AI Specialist able to do when the “Enrich event logs with conversation data" setting in Einstein Copilot is enabled?',
                'answers': [
                    ('View the user click path that led to each copilot action.', False),
                    ('View session data including user input and copilot responses for sessions over the past 7 days.', True),
                    ('Generate detailed reports on all Copilot conversations over any time period.', False),
                ],
            },
            {
                'text': 'Universal Containers’ current AI data masking rules do not align with organizational privacy and security policies and requirements. What should an AI Specialist recommend to resolve the issue?',
                'answers': [
                    ('Enable data masking for sandbox refreshes.', False),
                    ('Configure data masking in the Einstein Trust Layer setup.', True),
                    ('Add new data masking rules in LLM setup.', False),
                ],
            },
            {
                'text': 'Universal Containers wants to utilize Einstein for Sales to help sales reps reach their sales quotas by providing AI-generated plans containing guidance and steps for closing deals. Which feature should the AI Specialist recommend to the sales team?',
                'answers': [
                    ('Find Similar Deals', False),
                    ('Create Account Plan', False),
                    ('Create Close Plan', True),
                ],
            },
            {
                'text': 'Where should the AI Specialist go to add/update actions assigned to a copilot?',
                'answers': [
                    ('Copilot Actions page, the record page for the copilot action, or the Copilot Action Library tab', True),
                    ('Copilot Actions page or Global Actions', False),
                    ('Copilot Detail page, Global Actions, or the record page for the copilot action', False),
                ],
            },
            {
                'text': 'Northern Trail Outfitters (NTO) wants to configure Einstein Trust Layer in its production org but is unable to see the option on the Setup page. After provisioning Data Cloud, which step must an AI Specialist take to make this option available to NTO?',
                'answers': [
                    ('Turn on Einstein Copilot.', False),
                    ('Turn on Einstein Generative AI.', True),
                    ('Turn on Prompt Builder.', False),
                ],
            },
            {
                'text': 'An AI Specialist implements Einstein Sales Emails for a sales team. The team wants to send personalized follow-up emails to leads based on their interactions and data stored in Salesforce. The AI Specialist needs to configure the system to use the most accurate and up-to-date information for email generation. Which grounding technique should the AI Specialist use?',
                'answers': [
                    ('Ground with Apex Merge Fields', False),
                    ('Ground with Record Merge Fields', True),
                    ('Automatic grounding using Draft with Einstein feature', False),
                ],
            },
            {
                'text': 'Universal Containers wants to use an external large language model (LLM) in Prompt Builder. What should an AI Specialist recommend?',
                'answers': [
                    ('Use Apex to connect to an external LLM and ground the prompt.', False),
                    ('Use BYO-LLM functionality in Einstein Studio.', True),
                    ('Use Flow and External Services to bring data from an external LLM.', False),
                ],
            },
            {
                'text': 'A data scientist needs to view and manage models in Einstein Studio. The data scientist also needs to create prompt templates in Prompt Builder. Which permission sets should an AI Specialist assign to the data scientist?',
                'answers': [
                    ('Data Cloud Admin and Prompt Template Manager', True),
                    ('Prompt Template Manager and Prompt Template User', False),
                    ('Prompt Template User and Data Cloud Admin', False),
                ],
            },
            {
                'text': 'An AI Specialist wants to include data from the response of external service invocation (REST API callout) into the prompt template. How should the AI Specialist meet this requirement?',
                'answers': [
                    ('Convert the JSON to an XML merge field.', False),
                    ('Use External Service Record merge fields.', True),
                    ('Use “Add Prompt Instructions” flow element.', False),
                ],
            },
            {
                'text': 'Universal Containers tests out a new Einstein Generative AI feature for its sales team to create personalized and contextualized emails for its customers. Sometimes, users find that the draft email contains placeholders for attributes that could have been derived from the recipient\'s contact record. What is the most likely explanation for why the draft email shows these placeholders?',
                'answers': [
                    ('The user does not have Einstein Sales Emails permission assigned.', False),
                    ('The user does not have permission to access the fields.', True),
                    ('The user\'s locale language is not supported by Prompt Builder.', False),
                ],
            },
            {
                'text': 'What is the primary function of the planner service in the Einstein Copilot system?',
                'answers': [
                    ('Generating record queries based on conversation history', False),
                    ('Offering real-time language translation during conversations', False),
                    ('Identifying copilot actions to respond to user utterances', True),
                ],
            },
            {
                'text': 'Universal Containers (UC) wants to enable its sales team to get insights into product and competitor names mentioned during calls. How should UC meet this requirement?',
                'answers': [
                    ('Enable Einstein Conversation Insights, assign permission sets, define recording managers, and customize insights with up to 50 competitor names.', False),
                    ('Enable Einstein Conversation Insights, connect a recording provider, assign permission sets, and customize insights with up to 25 products.', False),
                    ('Enable Einstein Conversation Insights, enable sales recording, assign permission sets, and customize insights with up to 50 products.', True),
                ],
            },
            {
                'text': 'An AI Specialist is considering using a Field Generation prompt template type. What should the AI Specialist check before creating the Field Generation prompt to ensure it is possible for the field to be enabled for generative AI?',
                'answers': [
                    ('That the field chosen must be a rich text field with 255 characters or more.', False),
                    ('That the org is set to API version 59 or higher.', True),
                    ('That the Lightning page layout where the field will reside has been upgraded to Dynamic Forms.', False),
                ],
            },
            {
                'text': 'A sales rep at Universal Containers is extremely busy and sometimes will have very long sales calls on voice and video calls and might miss key details. They are just starting to adopt new generative AI features. Which Einstein Generative AI feature should an AI Specialist recommend to help the rep get the details they might have missed during a conversation?',
                'answers': [
                    ('Call Summary', True),
                    ('Call Explorer', False),
                    ('Sales Summary', False),
                ],
            },
            {
                'text': 'Before activating a custom copilot action, an AI Specialist would like to understand multiple real-world user utterances to ensure the action is being selected appropriately. Which tool should the AI Specialist recommend?',
                'answers': [
                    ('Model Playground', False),
                    ('Einstein Copilot', False),
                    ('Copilot Builder', True),
                ],
            },
            {
                'text': 'An AI Specialist built a Field Generation prompt template that worked for many records, but users are reporting random failures with token limit errors. What is the cause of the random nature of this error?',
                'answers': [
                    ('The number of tokens generated by the dynamic nature of the prompt template will vary by record.', True),
                    ('The template type needs to be switched to Flex to accommodate the variable amount of tokens generated by the prompt grounding.', False),
                    ('The number of tokens that can be processed by the LLM varies with total user demand.', False),
                ],
            },
            {
                'text': 'The marketing team at Universal Containers is looking for a way to personalize emails based on customer behavior, preferences, and purchase history. Why should the team use Einstein Copilot as the solution?',
                'answers': [
                    ('To generate relevant content when engaging with each customer', True),
                    ('To analyze past campaign performance', False),
                    ('To send automated emails to all customers', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) plans to send one of three different emails to its customers based on the customer\'s lifetime value score and their market segment. Considering that UC are required to explain why an email was selected, which AI model should UC use to achieve this?',
                'answers': [
                    ('Predictive model and generative model', False),
                    ('Generative model', False),
                    ('Predictive model', True),
                ],
            },
            {
                'text': 'Universal Containers recently launched a pilot program to integrate conversational AI into its CRM business operations with Einstein Copilot. How should the AI Specialist monitor Copilot\'s usability and the assignment of actions?',
                'answers': [
                    ('Run a report on the Platform Debug Logs', False),
                    ('Query the Copilot log data using the metadata API', False),
                    ('Run Einstein Copilot Analytics', True),
                ],
            },
            {
                'text': 'Universal Containers (UC) wants to use the Draft with Einstein feature in Sales Cloud to create a personalized introduction email. After creating a proposed draft email, which predefined adjustment should UC choose to revise the draft with a more casual tone?',
                'answers': [
                    ('Make Less Formal', True),
                    ('Enhance Friendliness', False),
                    ('Optimize for Clarity', False),
                ],
            },
            {
                'text': 'Universal Containers plans to implement prompt templates that utilize the standard foundation models. What should the AI Specialist consider when building prompt templates in Prompt Builder?',
                'answers': [
                    ('Include multiple-choice questions within the prompt to test the LLM\'s understanding of the context', False),
                    ('Ask it to role-play as a character in the prompt template to provide more context to the LLM', True),
                    ('Train LLM with data using different writing styles including word choice, intensifiers, emojis, and punctuation', False),
                ],
            },
            {
                'text': 'Leadership needs to populate a dynamic form field with a summary or description created by a large language model (LLM) to facilitate more productive conversations with customers. Leadership also wants to keep a human in the loop to be considered in their AI strategy. Which prompt template type should the AI Specialist recommend?',
                'answers': [
                    ('Sales Email', False),
                    ('Field Generation', False),
                    ('Record Summary', True),
                ],
            },
            {
                'text': 'Universal Containers wants to use an external large language model (LLM) in Prompt Builder. What should an AI Specialist recommend?',
                'answers': [
                    ('Use Apex to connect to an external LLM and ground the prompt', False),
                    ('Use BYO-LLM functionality in Einstein Studio', True),
                    ('Use Flow and External Services to bring data from an external LLM', False),
                ],
            },
            {
                'text': 'What is the main purpose of Prompt Builder?',
                'answers': [
                    ('A tool for developers to use in Visual Studio Code that creates prompts for Apex programming, assisting developers in writing code more efficiently.', False),
                    ('A tool that enables companies to create reusable prompts for large language models (LLMs), bringing generative AI responses to their flow of work', True),
                    ('A tool within Salesforce offering real-time AI-powered suggestions and guidance to users, improving productivity and decision-making.', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) has a mature Salesforce org with a lot of data in cases and Knowledge articles. UC is concerned that there are many legacy fields, with data that might not be applicable for Einstein AI to draft accurate email responses. Which solution should UC use to ensure Einstein AI can draft responses from a defined data source?',
                'answers': [
                    ('Service AI Grounding', True),
                    ('Work Summaries', False),
                    ('Service Replies', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) is implementing Einstein Generative AI to improve customer insights and interactions. UC needs audit and feedback data to be accessible for reporting purposes. What is a consideration for this requirement?',
                'answers': [
                    ('Storing this data requires Data Cloud to be provisioned', True),
                    ('Storing this data requires a custom object for data to be configured', False),
                    ('Storing this data requires Salesforce big objects', False),
                ],
            },
            {
                'text': 'Universal Containers wants to allow its service agents to query the current fulfilment status of an order with natural language. There is an existing auto launched flow to query the information from Oracle ERP, which is the system of record for the order fulfilment process. How should an AI Specialist apply the power of conversational AI to this use case?',
                'answers': [
                    ('Create a Flex prompt template in Prompt Builder', False),
                    ('Create a custom copilot action which calls a flow', True),
                    ('Configure the Integration Flow Standard Action in Einstein Copilot', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) wants to assess Salesforce\'s generative features but has concerns over its company data being exposed to third-party large language models (LLMs). Specifically, UC wants the following capabilities to be part of Einstein\'s generative AI service. No data is used for LLM training or product improvements by third-party LLMs. No data is retained outside of UC\'s Salesforce org. The data sent cannot be accessed by the LLM provider. Which property of the Einstein Trust Layer should the AI Specialist highlight to UC that addresses these requirements?',
                'answers': [
                    ('Prompt Defense', False),
                    ('Zero-Data Retention Policy', True),
                    ('Data Masking', False),
                ],
            },
            {
                'text': 'Universal Containers implemented Einstein Copilot for its users. One user complains that Einstein Copilot is not deleting activities from the past 7 days. What is the reason for this issue?',
                'answers': [
                    ('Einstein Copilot Delete Record Action permission is not associated to the user', False),
                    ('Einstein Copilot does not have the permission to delete the user\'s records', False),
                    ('Einstein Copilot does not support the Delete Record action', True),
                ],
            },
            {
                'text': 'An AI Specialist is tasked with configuring a generative model to create personalized sales emails using customer data stored in Salesforce. The AI Specialist has already fine-tuned a large language model (LLM) on the OpenAI platform. Security and data privacy are critical concerns for the client. How should the AI Specialist integrate the custom LLM into Salesforce?',
                'answers': [
                    ('Create an application of the custom LLM and embed it in Sales Cloud via iFrame', False),
                    ('Add the fine-tuned LLM in Einstein Studio Model Builder', True),
                    ('Enable model endpoint on OpenAI and make callouts to the model to generate emails', False),
                ],
            },
            {
                'text': 'Universal Containers is planning a marketing email about products that most closely match a customer\'s expressed interests. What should an AI Specialist recommend to generate this email?',
                'answers': [
                    ('Standard email marketing template using Apex or flows for matching interest in products', False),
                    ('Custom sales email template which is grounded with interest and product information', True),
                    ('Standard email draft with Einstein and choose standard email template', False),
                ],
            },
            {
                'text': 'Which feature in the Einstein Trust Layer helps to minimize the risks of jailbreaking and prompt injection attacks?',
                'answers': [
                    ('Secure Data Retrieval and Grounding', False),
                    ('Data Masking', False),
                    ('Prompt Defense', True),
                ],
            },

            {
                'text': 'Universal Containers recently launched a pilot program to integrate conversational AI into its CRM business operations with Einstein Copilot. How should the AI Specialist monitor Copilot\'s usability and the assignment of actions?',
                'answers': [
                    ('Run a report on the Platform Debug Logs', False),
                    ('Query the Copilot log data using the metadata API', False),
                    ('Run Einstein Copilot Analytics', True),
                ],
            },
            {
                'text': 'Universal Containers (UC) is implementing Einstein Generative AI to improve customer insights and interactions. UC needs audit and feedback data to be accessible for reporting purposes. What is a consideration for this requirement?',
                'answers': [
                    ('Storing this data requires Data Cloud to be provisioned', True),
                    ('Storing this data requires a custom object for data to be configured', False),
                    ('Storing this data requires Salesforce big objects', False),
                ],
            },
            {
                'text': 'Universal Containers is planning a marketing email about products that most closely match a customer\'s expressed interests. What should an AI Specialist recommend to generate this email?',
                'answers': [
                    ('Standard email marketing template using Apex or flows for matching interest in products', False),
                    ('Custom sales email template which is grounded with interest and product information', True),
                    ('Standard email draft with Einstein and choose standard email template', False),
                ],
            },

            {
                'text': 'Universal Containers wants to implement a solution in Salesforce with a custom UX that allows users to enter a sales order number. Subsequently, the system will invoke a custom prompt template to create and display a summary of the sales order header and sales order details. Which solution should an AI Specialist implement to meet this requirement?',
                'answers': [
                    ('Create a screen flow to collect sales order number and invoke the prompt template using the standard "Prompt Template" flow action.', True),
                    ('Create a template-triggered prompt flow and invoke the prompt template using the standard "Prompt Template" flow action.', False),
                    ('Create an auto launched flow and invoke the prompt template using the standard "Prompt Template" flow action.', False),
                ],
            },
            {
                'text': 'An AI Specialist at Universal Containers is working on a prompt template to generate personalized emails for product demonstration requests from customers. It is important for the AI-generated email to adhere strictly to the guidelines, using only associated opportunity information, and to encourage the recipient to take the desired action. How should the AI Specialist include these instructions on a new line in the prompt template?',
                'answers': [
                    ('Surround them with triple quotes (""").', True),
                    ('Make sure merged fields are defined.', False),
                    ('Use curly brackets {} to encapsulate instructions.', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) has recently received an increased number of support cases. As a result, UC has hired more customer support reps and has started to assign some of the ongoing cases to newer reps. Which generative AI solution should the new support reps use to understand the details of a case without reading through each case comment?',
                'answers': [
                    ('Einstein Copilot', False),
                    ('Einstein Sales Summaries', False),
                    ('Einstein Work Summaries', True),
                ],
            },
            {
                'text': 'An administrator wants to check the response of the Flex prompt template they\'ve built, but the preview button is greyed out. What is the reason for this?',
                'answers': [
                    ('The records related to the prompt have not been selected.', True),
                    ('The prompt has not been saved and activated.', False),
                    ('A merge field has not been inserted in the prompt.', False),
                ],
            },
            {
                'text': 'An AI Specialist configured Data Masking within the Einstein Trust Layer. How should the AI Specialist begin validating that the correct fields are being masked?',
                'answers': [
                    ('Use a Flow-based resource in Prompt Builder to debug the fields\' merge values using Flow Debugger.', False),
                    ('Request the Einstein Generative AI Audit Data from the Security section of the Setup menu.', True),
                    ('Enable the collection and storage of Einstein Generative AI Audit Data on the Einstein Feedback setup page.', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) uses Salesforce Service Cloud to support its customers and agents handling cases. UC is considering implementing Einstein Copilot and extending Service Cloud to mobile users. When would Einstein Copilot implementation be most advantageous?',
                'answers': [
                    ('When the goal is to streamline customer support processes and improve response times', True),
                    ('When the main objective is to enhance data security and compliance measures', False),
                    ('When the focus is on optimizing marketing campaigns and strategies', False),
                ],
            },
            {
                'text': 'A service agent is looking at a custom object that stores travel information. They recently received a weather alert and now need to cancel flights for the customers that are related with this itinerary. The service agent needs to review the Knowledge articles about canceling and rebooking the customer flights. Which Einstein Copilot capability helps the agent accomplish this?',
                'answers': [
                    ('Execute tasks based on available actions, answering questions using information from accessible Knowledge articles.', True),
                    ('Invoke a flow which makes a call to external data to create a Knowledge article.', False),
                    ('Generate a Knowledge article based off the prompts that the agent enters to create steps to cancel flights.', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) has a legacy system that needs to integrate with Salesforce. UC wishes to create a digest of account action plans using the generative API feature. Which API service should UC use to meet this requirement?',
                'answers': [
                    ('REST API', True),
                    ('Metadata API', False),
                    ('SOAP API', False),
                ],
            },
            {
                'text': 'Universal Containers is considering leveraging the Einstein Trust Layer in conjunction with Einstein Generative AI Audit Data. Which audit data is available using the Einstein Trust Layer?',
                'answers': [
                    ('Response accuracy and offensiveness score', False),
                    ('Hallucination score and bias score', False),
                    ('Masked data and toxicity score', True),
                ],
            },
            {
                'text': 'The AI Specialist of Northern Trail Outfitters reviewed the organization\'s data masking settings within the Configure Data Masking menu within Setup. Upon assessing all of the fields, a few additional fields were deemed sensitive and have been masked within Einstein\'s Trust Layer. Which steps should the AI Specialist take upon modifying the masked fields?',
                'answers': [
                    ('Turn off the Einstein Trust Layer and turn it on again.', False),
                    ('Test and confirm that the responses generated from prompts that utilize the data and masked data do not adversely affect the quality of the generated response', True),
                    ('Turn on Einstein Feedback so that end users can report if there are any negative side effects on AI features.', False),
                ],
            },

            {
                'text': 'An AI Specialist needs to create a prompt template to fill a custom field named Latest Opportunities Summary on the Account object with information from the three most recently opened opportunities. How should the AI Specialist gather the necessary data for the prompt template?',
                'answers': [
                    ('Create a flow to retrieve the opportunity information.', False),
                    ('Select the Account Opportunity object as a resource when creating the prompt template.', True),
                    ('Select the latest Opportunities related list as a merge field.', False),
                ],
            },
            {
                'text': 'Universal Containers is interested in improving the sales operation efficiency by analyzing their data using AI-powered predictions in Einstein Studio. Which use case works for this scenario?',
                'answers': [
                    ('Predict customer sentiment toward a promotion message.', False),
                    ('Predict customer lifetime value of an account.', False),
                    ('Predict most popular products from new product catalog.', True),
                ],
            },

            {
                'text': 'Universal Containers (UC) is using Einstein Generative AI to generate an account summary. UC aims to ensure the content is safe and inclusive, utilizing the Einstein Trust Layer\'s toxicity scoring to assess the content\'s safety level. What does a safety category score of 1 indicate in the Einstein Generative Toxicity Score?',
                'answers': [
                    ('Not safe', False),
                    ('Safe', True),
                    ('Moderately safe', False),
                ],
            },
            {
                'text': 'What is the correct process to leverage Prompt Builder in a Salesforce org?',
                'answers': [
                    ('Select the appropriate prompt template type to use, select one of Salesforce\'s standard prompts, determine the object to associate the prompt, select a record to validate against, and associate the prompt to an action.', False),
                    ('Select the appropriate prompt template type to use, develop the prompt within the prompt workspace, select resources to dynamically insert CRM-derived grounding data, pick the model to use, and test and validate the generated responses.', True),
                    ('Enable the target object for generative prompting, develop the prompt within the prompt workspace, select records to fine-tune and ground the response, enable the Trust Layer, and associate the prompt to an action.', False),
                ],
            },
            {
                'text': 'Universal Containers is evaluating Einstein Generative AI features to improve the productivity of the service center operation. Which features should the AI Specialist recommend?',
                'answers': [
                    ('Service Replies and Case Summaries', True),
                    ('Service Replies and Work Summaries', False),
                    ('Reply Recommendations and Sales Summaries', False),
                ],
            },
            {
                'text': 'Universal Containers\' service team wants to customize the standard case summary response from Einstein Copilot. What should the AI Specialist do to achieve this?',
                'answers': [
                    ('Customize the standard Record Summary template for the Case object.', False),
                    ('Summarize the Case with a standard copilot action.', False),
                    ('Create a custom Record Summary prompt template for the Case object.', True),
                ],
            },
            {
                'text': 'Universal Containers plans to enhance the customer support team\'s productivity using AI. Which specific use case necessitates the use of Prompt Builder?',
                'answers': [
                    ('Creating a draft of a support bulletin post for new product patches', True),
                    ('Creating an AI-generated customer support agent performance score', False),
                    ('Estimating support ticket volume based on historical data and seasonal trend', False),
                ],
            },
            {
                'text': 'Universal Containers is using Einstein Copilot for Sales to find similar opportunities to help close deals faster. The team wants to understand the criteria used by the copilot to match opportunities. What is one criteria that Einstein Copilot for Sales uses to match similar opportunities?',
                'answers': [
                    ('Matched opportunities are limited to the same account.', False),
                    ('Matched opportunities have a status of Closed Won from last 12 months.', True),
                    ('Matched opportunities were created in the last 12 months', False),
                ],
            },
            {
                'text': 'Universal Containers has an active standard email prompt template that does not fully deliver on the business requirements. Which steps should an AI Specialist take to use the content of the standard prompt email template in question and customize it to fully meet the business requirements?',
                'answers': [
                    ('Save as New Template and edit as needed.', False),
                    ('Clone the existing template and modify as needed.', True),
                    ('Save as New Version and edit as needed.', False),
                ],
            },
            {
                'text': 'In Model Playground, which hyperparameters of an existing Salesforce-enabled foundational model can an AI Specialist change?',
                'answers': [
                    ('Temperature, Top-k sampling, Presence Penalty', False),
                    ('Temperature, Frequency Penalty, Output Tokens', False),
                    ('Temperature, Frequency Penalty, Presence Penalty', True),
                ],
            },
            {
                'text': 'Universal Containers implements Custom Copilot Actions to enhance its customer service operations. The development team needs to understand the core components of a Custom Copilot Action to ensure proper configuration and functionality. What should the development team review in the Custom Copilot Action configuration to identify one of the core components of a Custom Copilot Action?',
                'answers': [
                    ('Output Types', False),
                    ('Action Triggers', False),
                    ('Instructions', True),
                ],
            },
            {
                'text': 'A Salesforce Administrator is exploring the capabilities of Einstein Copilot to enhance user interaction within their organization. They are particularly interested in how Einstein Copilot processes user requests and the mechanism it employs to deliver responses. The administrator is evaluating whether Einstein Copilot directly interfaces with a large language model (LLM) to fetch and display responses to user inquiries, facilitating a broad range of requests from users. How does Einstein Copilot handle user requests in Salesforce?',
                'answers': [
                    ('Einstein Copilot analyzes the user’s request and LLM technology is used to generate and display the appropriate response.', True),
                    ('Einstein Copilot will trigger a flow that utilizes a prompt template to generate the response.', False),
                ],
            },
            {
                'text': 'How does the Einstein Trust Layer ensure that sensitive data is protected while generating useful and meaningful responses?',
                'answers': [
                    ('Masked data will be de-masked during the request journey.', False),
                    ('Responses that do not meet the relevance threshold will be automatically rejected.', False),
                    ('Masked data will be de-masked during the response journey.', True),
                ],
            },

            {
                'text': 'An administrator is responsible for ensuring the security and reliability of Universal Containers\' (UC) CRM data. UC needs enhanced data protection and up-to-date AI capabilities. UC also needs to include relevant security considerations in AI interactions. Which option should the administrator implement?',
                'answers': [
                    ('Enable Salesforce admin users to create and train custom large language models (LLMs) with CRM data.', False),
                    ('Bring together a conversational interface for interacting with AI for all Salesforce users, such as developers and eCommerce retailers.', True),
                    ('Enable data scientists to train predictive AI models with historical CRM data using built-in machine learning capabilities.', False),
                ],
            },
            {
                'text': 'Universal Containers (UC) wants to offer personalized service experiences and reduce agent handling time with AI-generated email responses grounded in Knowledge base. Which AI capability should UC use?',
                'answers': [
                    ('Einstein Email Replies', False),
                    ('Einstein Generative Service Replies for Email', False),
                    ('Einstein Service Replies for Email', True),
                ],
            },
            {
                'text': 'Where should the AI Specialist go to add/update actions assigned to the copilot?',
                'answers': [
                    ('Copilot Detail page, Global Actions, or the record page for the copilot action.', False),
                    ('Copilot Actions page or Global Actions.', False),
                    ('Copilot Actions page, the record page for the copilot action, or the Copilot Action Library.', True),
                ],
            },
            {
                'text': 'Universal Containers wants to make a sales proposal and directly use data from multiple unrelated objects (standard and custom) in a prompt template. What should the AI Specialist recommend?',
                'answers': [
                    ('Create a Flex template to add resources with standard and custom objects as inputs.', True),
                    ('Create a prompt template-triggered flow to access the data from standard and custom objects.', False),
                    ('Create a prompt template passing in a special custom object that connects the records temporarily.', False),
                ],
            },
            {
                'text': 'How does the Einstein Trust Layer ensure that sensitive data is protected while generating useful and meaningful responses?',
                'answers': [
                    ('Masked data will be de-masked during the request journey.', False),
                    ('Responses that do not meet the relevance threshold will be automatically rejected.', False),
                    ('Masked data will be de-masked during the response journey.', True),
                ],
            },
            {
                'text': 'An AI Specialist has created a Copilot custom action using flow as the reference action type. However, it is not delivering the expected results to the conversation preview, and therefore needs troubleshooting. What should the AI Specialist do to identify the root cause of the problem?',
                'answers': [
                    ('In Copilot Builder within the Dynamic Panel, confirm the selected action and observe the values in the Input and Output sections.', False),
                    ('In Copilot Builder, verify the utterance entered by the user and review session event debug information.', True),
                    ('In Copilot Builder within the Dynamic Panel, turn on dynamic debugging to show the inputs and outputs.', False),
                ],
            },
            {
                'text': 'An AI Specialist at Universal Containers (UC) is tasked with creating a new custom prompt template to populate a field with generated output. UC enabled the Einstein Trust Layer to ensure AI Audit data is captured and monitored for adoption and possible enhancements. Which prompt template type should the AI Specialist use and which consideration should they review?',
                'answers': [
                    ('Field Generation, and that Dynamic Forms is enabled.', True),
                    ('Flex, and that Dynamic Fields is enabled.', False),
                    ('Field Generation, and that Dynamic Fields is enabled.', False),
                ],
            },

        ]

        for question_data in questions_data:
                # Automatically set multiple_correct if more than one answer is correct
                multiple_correct = sum(1 for answer in question_data['answers'] if answer[1]) > 1
                question = Question.objects.create(
                    exam=exam,
                    text=question_data['text'],
                    multiple_correct=multiple_correct
                )
                for answer_text, is_correct in question_data['answers']:
                    Answer.objects.create(question=question, text=answer_text, is_correct=is_correct)

class Migration(migrations.Migration):

    dependencies = [
        # Add your app's dependencies here
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_ai_specialist, atomic=False),
    ]
